version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Initialize DB
    networks:
      fastapi-network:
        ipv4_address: 172.28.0.3
    ports:
      - "5432:5432"
    depends_on:
      - fluentd
    extra_hosts:
      - "fluentd:172.28.0.2"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "172.28.0.2:24224"
        tag: "docker.db"

  app:
    build: ./app
    volumes:
      - ./app:/app
    depends_on:
      - db
      - fluentd
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/mydb
      - PYTHONPATH=/app
    networks:
      fastapi-network:
        ipv4_address: 172.28.0.4
    ports:
      - "8000:8000"
    extra_hosts:
      - "fluentd:172.28.0.2"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "172.28.0.2:24224"
        tag: "docker.app"

  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    environment:
      - FLUENTD_CONF=fluent.conf
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      fastapi-network:
        ipv4_address: 172.28.0.2
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "24220:24220"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:24220/api/plugins.json" ]
      interval: 30s
      timeout: 10s
      retries: 3

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    networks:
      fastapi-network:
        ipv4_address: 172.28.0.5
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    depends_on:
      - elasticsearch
    networks:
      fastapi-network:
        ipv4_address: 172.28.0.6
    ports:
      - "5601:5601"

volumes:
  pgdata:

networks:
  fastapi-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
