version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Initialize DB
    networks:
      - fastapi-network
    ports:
      - "5432:5432"

  app:
    build: ./app
    container_name: fastapi_app
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - PYTHONPATH=/app
    networks:
      - fastapi-network
    ports:
      - "8000:8000"

volumes:
  pgdata:

networks:
  fastapi-network:
    driver: bridge
