FROM python:3.11-slim

# Install git to clone the repository
RUN apt-get update && apt-get install -y git

# Clone the latest FastAPI project from GitHub
RUN git clone https://github.com/rdrishabh38/fastapi-demo.git /fastapi-demo

# Create a virtual environment inside the project
RUN python -m venv venv
RUN venv/bin/pip install --upgrade pip

# Install dependencies inside the virtual environment
RUN venv/bin/pip install --no-cache-dir -r requirements.txt

# Expose FastAPI's default port
EXPOSE 8000

# Set the working directory to the project root
WORKDIR /fastapi-demo/app

# Run FastAPI inside the virtual environment
CMD ["/bin/sh", "-c", "../venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000"]
